name: aura_music
description: "A breathtakingly beautiful music streaming application"
publish_to: "none"
version: 1.7.0+7

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.5.1

  # Navigation
  go_router: ^14.2.7

  # Audio
  just_audio: ^0.9.40
  audio_service: ^0.18.15
  just_audio_background: ^0.0.1-beta.13

  # Networking
  dio: ^5.7.0
  cached_network_image: ^3.4.1

  # Local Storage
  shared_preferences: ^2.3.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.4

  # UI
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.0
  shimmer: ^3.0.0
  palette_generator: ^0.3.3+4

  # Utilities
  uuid: ^4.5.1
  intl: ^0.19.0
  permission_handler: ^11.3.1
  device_info_plus: ^10.1.2
  share_plus: ^10.0.3
  url_launcher: ^6.3.1
  speech_to_text: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  hive_generator: ^2.0.1
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.4.1
  id3: ^1.0.2

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/

  # Uncomment after adding Manrope font files to assets/fonts/
  # fonts:
  #   - family: Manrope
  #     fonts:
  #       - asset: assets/fonts/Manrope-Regular.ttf
  #       - asset: assets/fonts/Manrope-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Manrope-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/Manrope-Bold.ttf
  #         weight: 700

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/real_app_icon.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/real_app_icon.png"

flutter_native_splash:
  color: "#000000"
  image: assets/real_app_icon.png
  android: true
  ios: false
  android_12:
    color: "#000000"
    image: assets/real_app_icon.png
